base:
  taker_fee_bps: 2.5
  maker_fee_bps: 1.0
  slippage_bps: 3.0
plus_50:
  taker_fee_bps: 3.75
  maker_fee_bps: 1.5
  slippage_bps: 4.5
double:
  taker_fee_bps: 5.0
  maker_fee_bps: 2.0
  slippage_bps: 6.0
